addr: ':8080'
env: 'development'

http:
  read_timeout: '10s'
  write_timeout: '15s'
  idle_timeout: '60s'
  request_timeout: '30s'

logger:
  level: 'info'
  app: 'my-app'
  service: 'my-service'
  udp_address: ''
  enable_caller: false
