addr: ':8080'
env: 'production'

http:
  read_timeout: '5s'
  write_timeout: '10s'
  idle_timeout: '120s'
  request_timeout: '15s'

logger:
  level: 'info'
  app: 'my-app'
  service: 'my-service'
  udp_address: ''
  enable_caller: false
